# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\raphael\OneDrive\Documents\python_sandbox\exa_arb_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExatronARB(object):
    def setupUi(self, ExatronARB):
        ExatronARB.setObjectName("ExatronARB")
        ExatronARB.resize(811, 695)
        ExatronARB.setAcceptDrops(True)
        self.centralwidget = QtWidgets.QWidget(ExatronARB)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.interfaceBox = QtWidgets.QComboBox(self.centralwidget)
        self.interfaceBox.setObjectName("interfaceBox")
        self.horizontalLayout_3.addWidget(self.interfaceBox)
        self.tcpPortBox = QtWidgets.QSpinBox(self.centralwidget)
        self.tcpPortBox.setMaximum(65535)
        self.tcpPortBox.setProperty("value", 4000)
        self.tcpPortBox.setObjectName("tcpPortBox")
        self.horizontalLayout_3.addWidget(self.tcpPortBox)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_3.addWidget(self.connectButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.getTempVal = QtWidgets.QLCDNumber(self.centralwidget)
        self.getTempVal.setMinimumSize(QtCore.QSize(0, 39))
        self.getTempVal.setSmallDecimalPoint(False)
        self.getTempVal.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.getTempVal.setProperty("value", 25.5)
        self.getTempVal.setObjectName("getTempVal")
        self.horizontalLayout.addWidget(self.getTempVal)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.logBrowser = QtWidgets.QTextEdit(self.centralwidget)
        self.logBrowser.setObjectName("logBrowser")
        self.verticalLayout.addWidget(self.logBrowser)
        ExatronARB.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ExatronARB)
        self.statusbar.setObjectName("statusbar")
        ExatronARB.setStatusBar(self.statusbar)
        self.actionGogo = QtWidgets.QAction(ExatronARB)
        self.actionGogo.setObjectName("actionGogo")

        self.retranslateUi(ExatronARB)
        QtCore.QMetaObject.connectSlotsByName(ExatronARB)

    def retranslateUi(self, ExatronARB):
        _translate = QtCore.QCoreApplication.translate
        ExatronARB.setWindowTitle(_translate("ExatronARB", "MainWindow"))
        self.connectButton.setText(_translate("ExatronARB", "Connect"))
        self.label_2.setText(_translate("ExatronARB", "TEMP LIST"))
        self.label.setText(_translate("ExatronARB", "PARTS LIST ##"))
        self.actionGogo.setText(_translate("ExatronARB", "gogo"))
